### ISSUE TITLE
V2 - Proposal: Renaming src/index.js 

### ISSUE THREAD

**Issue by sthzg** [react-webpack-generators/react-webpack-template#41]
I would propose renaming `src/index.js` for two reasons:

1. tooling
2. extendability

1) Various editors/ides will support some kind of file opening dialog. Due to `index.js` being npm's default name for packages and often being used as an entry point for package exports, looking only for `index.js` in a regular project brings up many files.

2) To extend the setup, e.g. for server-side-rendering, we often create a second entry point for the server build. A naming pair of `server.js` and `client.js` (or whatever) is more self-documenting than e.g. `index.js` and `client.js`.

**Comment by weblogixx** [comment]
Seems like a good idea. I know the question arose last time, but I am not sure yet if we should support server side rendering out of the box. Most people do not even seem to react use it that way. That said, if there are enough supporters for such  feature, I will happily accept a pr ;)

**Comment by sthzg** [comment]
I'd find it cool if as a first step we simply renamed the `index.js` for above reasons. 

It would then be interesting to (along with the Wiki and possibly moving the generator project to an organization?) create a new repository, e.g. `react-webpack-generator-examples`. 

We could use that as a _monorepo_ to provide various setups of the generator to illustrate the questions that come up often (how do I integrate it with react-router, how do I integrate it with Redux, Alt, how can I achieve SSR, how can I build static websites from it, ...).

This type of demo repos is very common in the Spring Boot ecosystem, e.g.

```
react-webpack-generator-examples
  /setup-with-react-router/
  /setup-with-react-bootstrap/
  /setup-with-flux/
  /setup-with-static-site-generation/
```

Each of those first-level directories is a separate setup, so users can jump into each of them, hit npm install, and explore an isolated setup for the use case.

This example repo could also be a good source for prototyping stuff that may or may not become a part of the generator or the template.

E.g., I don't think that SSR can be generically integrated, as there is not _the one way_ of doing it. But it could be integrated with new prompts during installation, that set it up only if the user opts in (like many other options in the old and new generator).

**Comment by weblogixx** [comment]
@sthzg, sounds great. I will create the org on the weekend and maybe move the template to it as the first basic project. I will inform you when its done and the rights are set up correctly.

**Comment by weblogixx** [comment]
Done and merged.
