### ISSUE TITLE
V1 -- Remove --open call on npm start

### ISSUE THREAD

**Issue by sthzg** [react-webpack-generators/react-webpack-template#47]
As brought up in [generator-react-webpack #266](https://github.com/react-webpack-generators/generator-react-webpack/issues/266#issuecomment-239012817) 

**V1**
- [x] remove `open()` method in `server.js`
- [x] log dev server address to console after the inital webpack build is ready

**Comment by sthzg** [comment]
@weblogixx it will now print the following info the shell after the initial build on V1 of the template.

![bildschirmfoto 2016-08-11 um 12 14 13](https://cloud.githubusercontent.com/assets/1827893/17585742/aedd508c-5fbd-11e6-87dc-47e62670d578.png)

**Comment by weblogixx** [comment]
Seems like a nice addition. Do you think we should wait a bit until more 1.x features are there or do you want to push it directly? I do not think that we will have any more advanced features for the current stable, so pushing would ok.

**Comment by sthzg** [comment]
I think waiting is absolutely okay. I just want to merge it so that I can delete the feature branch. Besides being a topic in the browser sync issue it's not such an important change, after all.
