### ISSUE TITLE
V2 -- Upgrading to react-hot-loader v3?

### ISSUE THREAD

**Issue by sthzg** [react-webpack-generators/react-webpack-template#66]
@weblogixx I remember talking about HMR/hot-reloading briefly. Did you consider or have any experience with using [v3](https://github.com/gaearon/react-hot-loader/releases/tag/v3.0.0-beta.1) (currently in beta) with the template? I am starting a test on one project now but was curious because I remember that you were talking about some HMR issues while working on the new repos.

**Comment by weblogixx** [comment]
Hi @sthzg, yes, indeed we did. I have not tried v3 as there is currently no documentation (at least not officially, there seems to exist a pr on the repo which shows how to configure). The reasons I thought about canceling support for hmr was:

- When using flux or datasources, you will use them on componentWillMount, making hot reloading pointless (see https://github.com/react-webpack-generators/generator-react-webpack/issues/281#issuecomment-243826453)
- When using pure components, it will not work and you have to reload by yourself.

However there are still cases where it is a nice feature - thats the reason it is still in there. If you want we could include it (maybe in a feature branch?) and test if it works better now :)

**Comment by sthzg** [comment]
@weblogixx I have to admit that I don't have a deep understanding of the hot reloading infrastructure. V3 is reported to support hot reloading with 

1. Redux reducers 
2. stateless components (haven't found sth. about pure render mixin/PureComponent)
3. react-router (but not with async routes as this seems blocked by a react-router issue)

I don't know enough yet if 1. means that it can be made to work with real Flux implementations (like FB's flux or AltJS).

The documentation consists of two or three issues with lots of information. Will watch that for a while and experiment with it, but I don't think that any other immediate action than following its progress makes sense right now.

Closing it for now. Feel free to open it again anytime (or request to open it again if you see urgent use cases).
