### ISSUE TITLE
V2 -- Redundant entry in webpack Base

### ISSUE THREAD

**Issue by stylesuxx** [react-webpack-generators/react-webpack-template#75]
The entry in Base.js is overwritten from either dev, dist or test from what I can see. As far as I understand it points to the wrong entry file, but since it is never used, I guess it does not matter.

Should this be removed? Or at least adjusted to client.js?

Reported here => https://github.com/stylesuxx/generator-react-webpack-redux/issues/56

**Comment by sthzg** [comment]
Good catch, IMO it should be updated to point to `client.js`, as it is possible (if unlikely) that someone extends from the base config wo/ changing anything (e.g. when invoking the new `setupenv` subgen that does not add anything to the config itself but only extends base). I will do this in the next few minutes.
